### ISSUE TITLE
1.17报错版本不兼容

### ISSUE THREAD

**Issue by ghost** [lovexyn0827/Minecraft-World-Manipulation-Enchantment-Mod#2]
messmod-mc1.17-0.2.0+v20220827-BETA.jar 
1.17.1 fabric 0.14.9
其他的mod：
fabricAPI 0.46.1
fabric-carpet-1.4.57
报错信息：
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'MessMod' (messmod) 0.2.0+v20220827-BETA with any version that is compatible with:
		 - minecraft 1.17.1
Unmet dependency listing:
	 - Mod 'MessMod' (messmod) 0.2.0+v20220827-BETA requires any 1.18.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.17.1!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by lovexyn0827** [comment]
版本上传错了，非常抱歉。
