### ISSUE TITLE
1.16版本与carpet不兼容启动直接崩溃

### ISSUE THREAD

**Issue by ghost** [lovexyn0827/Minecraft-World-Manipulation-Enchantment-Mod#3]
[14:32:42] [main/INFO]: Loading Minecraft 1.16.5 with Fabric Loader 0.14.9
[14:32:43] [main/INFO]: Loading 50 mods:
	- carpet 1.4.44
	- fabric 0.42.0+1.16
	- fabric-api-base 0.4.0+3cc0f0907d via fabric
	- fabric-api-lookup-api-v1 1.3.1+3cc0f0907d via fabric
	- fabric-biome-api-v1 3.1.13+3cc0f0907d via fabric
	- fabric-blockrenderlayer-v1 1.1.6+3cc0f0907d via fabric
	- fabric-command-api-v1 1.1.3+3cc0f0907d via fabric
	- fabric-commands-v0 0.2.3+3cc0f0907d via fabric
	- fabric-containers-v0 0.1.12+3cc0f0907d via fabric
	- fabric-content-registries-v0 0.2.5+3cc0f0907d via fabric
	- fabric-crash-report-info-v1 0.1.4+3cc0f0907d via fabric
	- fabric-dimensions-v1 2.0.8+3cc0f0907d via fabric
	- fabric-entity-events-v1 1.2.4+3cc0f0907d via fabric
	- fabric-events-interaction-v0 0.4.5+3cc0f0907d via fabric
	- fabric-events-lifecycle-v0 0.2.2+3cc0f0907d via fabric
	- fabric-game-rule-api-v1 1.0.7+3cc0f0907d via fabric
	- fabric-item-api-v1 1.2.2+3cc0f0907d via fabric
	- fabric-item-groups-v0 0.3.1+3cc0f0907d via fabric
	- fabric-key-binding-api-v1 1.0.5+3cc0f0907d via fabric
	- fabric-keybindings-v0 0.2.2+3cc0f0907d via fabric
	- fabric-lifecycle-events-v1 1.2.2+3cc0f0907d via fabric
	- fabric-loot-tables-v1 1.0.3+3cc0f0907d via fabric
	- fabric-mining-levels-v0 0.1.4+3cc0f0907d via fabric
	- fabric-models-v0 0.3.1+3cc0f0907d via fabric
	- fabric-networking-api-v1 1.0.5+3cc0f0907d via fabric
	- fabric-networking-blockentity-v0 0.2.9+3cc0f0907d via fabric
	- fabric-networking-v0 0.3.3+3cc0f0907d via fabric
	- fabric-object-builder-api-v1 1.9.6+3cc0f0907d via fabric
	- fabric-object-builders-v0 0.7.3+3cc0f0907d via fabric
	- fabric-particles-v1 0.2.5+3cc0f0907d via fabric
	- fabric-registry-sync-v0 0.7.6+3cc0f0907d via fabric
	- fabric-renderer-api-v1 0.4.5+3cc0f0907d via fabric
	- fabric-renderer-indigo 0.4.5+3cc0f0907d via fabric
	- fabric-renderer-registries-v1 2.3.1+3cc0f0907d via fabric
	- fabric-rendering-data-attachment-v1 0.1.6+3cc0f0907d via fabric
	- fabric-rendering-fluids-v1 0.1.15+3cc0f0907d via fabric
	- fabric-rendering-v0 1.1.3+3cc0f0907d via fabric
	- fabric-rendering-v1 1.6.1+3cc0f0907d via fabric
	- fabric-resource-loader-v0 0.4.8+3cc0f0907d via fabric
	- fabric-screen-api-v1 1.0.1+3cc0f0907d via fabric
	- fabric-screen-handler-api-v1 1.1.6+3cc0f0907d via fabric
	- fabric-structure-api-v1 1.1.12+3cc0f0907d via fabric
	- fabric-tag-extensions-v0 1.1.2+3cc0f0907d via fabric
	- fabric-textures-v0 1.0.7+3cc0f0907d via fabric
	- fabric-tool-attribute-api-v1 1.2.8+3cc0f0907d via fabric
	- fabric-transfer-api-v1 1.5.0+3cc0f0907d via fabric
	- fabricloader 0.14.9
	- java 17
	- messmod 0.2.0+v20220827-BETA
	- minecraft 1.16.5
[14:32:43] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/zzwxh/AppData/Local/PCL2/.minecraft/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[14:32:47] [main/ERROR]: Mixin apply for mod carpet failed carpet.mixins.json:StructureBlockBlockEntity_limitsMixin from mod carpet -> net.minecraft.class_2633: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("CONSTANT") on net/minecraft/class_2633::outlineRenderDistanceLimit with priority 1000 cannot inject into net/minecraft/class_2633::method_11006()D merged by lovexyn0827.mess.mixins.StructureBlockBlockEntityMixin with priority 1000 [PREINJECT Applicator Phase -> carpet.mixins.json:StructureBlockBlockEntity_limitsMixin from mod carpet -> Prepare Injections ->  -> constant$zzl000$outlineRenderDistanceLimit(D)D -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("CONSTANT") on net/minecraft/class_2633::outlineRenderDistanceLimit with priority 1000 cannot inject into net/minecraft/class_2633::method_11006()D merged by lovexyn0827.mess.mixins.StructureBlockBlockEntityMixin with priority 1000 [PREINJECT Applicator Phase -> carpet.mixins.json:StructureBlockBlockEntity_limitsMixin from mod carpet -> Prepare Injections ->  -> constant$zzl000$outlineRenderDistanceLimit(D)D -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1338) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:835) ~[client-intermediary.jar:?]
	at net.minecraft.class_3523.<clinit>(class_3523.java:13) ~[client-intermediary.jar:?]
	at net.minecraft.class_5471.<clinit>(class_5471.java:11) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30573(class_5458.java:44) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:75) ~[client-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) [?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:74) [client-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:237) [client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:42) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:137) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.9.jar:?]
[14:32:47] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.9.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_3523.<clinit>(class_3523.java:13) ~[client-intermediary.jar:?]
	at net.minecraft.class_5471.<clinit>(class_5471.java:11) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30573(class_5458.java:44) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:75) ~[client-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:74) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:237) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:42) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:137) ~[1.16.5-Fabric%200.14.9.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.9.jar:?]
	... 2 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2633 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:419) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:835) ~[client-intermediary.jar:?]
	at net.minecraft.class_3523.<clinit>(class_3523.java:13) ~[client-intermediary.jar:?]
	at net.minecraft.class_5471.<clinit>(class_5471.java:11) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30573(class_5458.java:44) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:75) ~[client-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:74) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:237) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:42) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:137) ~[1.16.5-Fabric%200.14.9.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.9.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:835) ~[client-intermediary.jar:?]
	at net.minecraft.class_3523.<clinit>(class_3523.java:13) ~[client-intermediary.jar:?]
	at net.minecraft.class_5471.<clinit>(class_5471.java:11) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30573(class_5458.java:44) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:75) ~[client-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:74) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:237) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:42) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:137) ~[1.16.5-Fabric%200.14.9.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.9.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [carpet.mixins.json:StructureBlockBlockEntity_limitsMixin from mod carpet] from phase [DEFAULT] in config [carpet.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:835) ~[client-intermediary.jar:?]
	at net.minecraft.class_3523.<clinit>(class_3523.java:13) ~[client-intermediary.jar:?]
	at net.minecraft.class_5471.<clinit>(class_5471.java:11) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30573(class_5458.java:44) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:75) ~[client-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:74) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:237) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:42) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:137) ~[1.16.5-Fabric%200.14.9.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.9.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("CONSTANT") on net/minecraft/class_2633::outlineRenderDistanceLimit with priority 1000 cannot inject into net/minecraft/class_2633::method_11006()D merged by lovexyn0827.mess.mixins.StructureBlockBlockEntityMixin with priority 1000 [PREINJECT Applicator Phase -> carpet.mixins.json:StructureBlockBlockEntity_limitsMixin from mod carpet -> Prepare Injections ->  -> constant$zzl000$outlineRenderDistanceLimit(D)D -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1338) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:835) ~[client-intermediary.jar:?]
	at net.minecraft.class_3523.<clinit>(class_3523.java:13) ~[client-intermediary.jar:?]
	at net.minecraft.class_5471.<clinit>(class_5471.java:11) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30573(class_5458.java:44) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:75) ~[client-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:74) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:237) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:42) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:137) ~[1.16.5-Fabric%200.14.9.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.9.jar:?]
	... 2 more

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 7 64bit]
 - Java Version [e.g. Java 1.8.0_241 64bit, OpenJDK build 11+28]

**Additional context**
Add any other context about the problem here. It could be screenshots, the crash report, the save where you have found the problem, or something else.

**Comment by ghost** [comment]
好像是mixin注入的问题

**Comment by lovexyn0827** [comment]
与地毯端1.4.25引入的structureBlockOutlineDistance选项有关，现已修复。1.17、1.18经检查测试不受影响。
