### ISSUE TITLE
Game crashes when rendering the name of an entity

### ISSUE THREAD

**Issue by redleaf1221** [lovexyn0827/Minecraft-World-Manipulation-Enchantment-Mod#8]
**Describe the bug**
When pointing to an armor stand with a name formed by JSON texts, game crashes.

**To Reproduce**
1. Run `/summon minecraft:armor_stand ^ ^ ^-10 {CustomName: '{"text":"Test","color":"dark_red","bold":true}'}` to spawn an armor stand behind player.
2. Turn back and look at the armor stand.
3. Game is suspended and then crashes.

**Expected behavior**
The name of the armor stand should be shown correctly.

**Desktop:**
 - OS: Windows 10 64bit
 - Version: MessMod 0.7.1+v20240112-BETA

**Log**
```
java.lang.ClassCastException: class net.minecraft.class_8828$class_2585 cannot be cast to class java.lang.String (net.minecraft.class_8828$class_2585 is in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @49993335; java.lang.String is in module java.base of loader 'bootstrap')
	at lovexyn0827.mess.rendering.hud.data.DataType$4.getStringOf(DataType.java:30)
	at lovexyn0827.mess.rendering.hud.data.BuiltinHudInfo.getFrom(BuiltinHudInfo.java:69)
	at lovexyn0827.mess.rendering.hud.data.LocalDataStorage.updateData(LocalDataStorage.java:23)
	at lovexyn0827.mess.rendering.hud.data.HudDataSender.updateLookingAtEntityData(HudDataSender.java:85)
	at lovexyn0827.mess.rendering.hud.ServerHudManager.tick(ServerHudManager.java:45)
	at lovexyn0827.mess.MessMod.onServerTicked(MessMod.java:90)
	at net.minecraft.server.MinecraftServer.handler$zle000$messmod$onTicked(MinecraftServer.java:4382)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:874)
	at net.minecraft.class_1132.method_3748(class_1132.java:110)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:683)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
[latest.log](https://github.com/lovexyn0827/MessMod/files/14075452/latest.log)
[crash-2024-01-28_16.47.31-server.txt](https://github.com/lovexyn0827/MessMod/files/14075453/crash-2024-01-28_16.47.31-server.txt)

**Comment by lovexyn0827** [comment]
Fixed in [MessMod 0.7.2+v20240129-BETA](https://modrinth.com/mod/messmod/version/cfyFw6Rt)

Thanks for reporting!
